### ISSUE TITLE
nullsafety version for getx package needs tobe updated

### ISSUE THREAD

**Issue by prakash-indorkar** [MarceloRab/search_app_bar_page#4]
Hi, Getx package is updating to null safety, and also other packages do as well. I am getting this error while using Getx null safety version.

`Because search_app_bar_page 1.5.1 depends on get ^3.25.4 and no versions of search_app_bar_page match >1.5.1 <2.0.0, search_app_bar_page ^1.5.1 requires get ^3.25.4.`

Please help to get this going, my app depends on your package. I'm also using the get_async_page package of yours. And both need updates.

Thanks, Prakash

**Comment by MarceloRab** [comment]
I am waiting for the update to get to update the search_app_bar_page. Today I updated all packages to the latest versions.

**Comment by prakash-indorkar** [comment]
Thanks Marcelo!.

I'm not sure if you are waiting for final update on getx to nullsafety or can we do it with pre-release for now.

Getx has null safety prerelease now. https://pub.dev/packages/get/versions/4.0.0-nullsafety.2

Regards, Prakash

**Comment by MarceloRab** [comment]
You can now use a pre-release version.

https://pub.dev/packages/search_app_bar_page

Published March 6, 2021 • Latest: 1.6.0 / Pre-release: 2.0.0-nullsafety.2
