### ISSUE TITLE
Sort function

### ISSUE THREAD

**Issue by Errichamonda** [MarceloRab/search_app_bar_page#5]
Hi, I would like to have a sort callback to sort my list by my parameters (and not by toString())

I have a big list of data that I need to sort by different parameters chosen by the end user.

Thanks in advance.

**Comment by MarceloRab** [comment]
Hi, @Errichamonda 
I use String because every query typed is in String. That is, we type a String in Search to, from it, filter the list. That way I can compare what you want to look for with the list.

**Comment by MarceloRab** [comment]
But you can demonstrate an example to help you with the solution.

Note that changing String types will bring a lot more complexity to the package.

**Comment by MarceloRab** [comment]
Hi, @Errichamonda

I just updated a new version with your order. 👍

See some recommendations.
https://pub.dev/packages/search_app_bar_page/changelog

See the SearchAppBarPage example for more details.
https://pub.dev/packages/search_app_bar_page/example

**Comment by Errichamonda** [comment]
Thanks! I'll look into it tomorrow and see if there are any problem. Thanks in advance for your quick response and change.

**Comment by MarceloRab** [comment]
All right @Errichamonda. 

Share your experience.

**Comment by Errichamonda** [comment]
> All right @Errichamonda.
> 
> Share your experience.

Sorry for the late response, I'm currently away from my work. I'll look into it next week.

**Comment by MarceloRab** [comment]
OK. The update has already been performed to enable using setState in the SearchPage widget with new sortFunction parameter. In other words, reset SearchPage with new parameters. Waiting for something new before closing issue.
