### ISSUE TITLE
[GETX] Worker [ever] disposed

### ISSUE THREAD

**Issue by jlucasguedes** [MarceloRab/search_app_bar_page#6]
Sou novo em Flutter, ao usar pacote app retorna na depuração [GETX] Worker [ever] disposed

**Comment by MarceloRab** [comment]
@jlucasguedes Desculpe a demora. Meu Mac antigo queimou o disco rígido.

Sobre sua pergunta. São logs do que acontece ao fechar a página. Precisa da dispose em streams para economizar memória. Você apresenta algum erro ou apenas encontrou a mensagem?

**Comment by MarceloRab** [comment]
Devido falta de resposta.
